### ISSUE TITLE
CB1 - Only reachable via IPv6 not via IPv4

### ISSUE THREAD

**Issue by LsHallo** [bigtreetech/CB1#111]
I'm trying to connect to my CB1 via IPv4
I've got the IP address:

```
biqu@BTT-CB1:~$  ip a
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether aa:aa:aa:aa:aa brd ff:ff:ff:ff:ff:ff
    inet 192.168.178.17/24 brd 192.168.178.255 scope global noprefixroute wlan0
       valid_lft forever preferred_lft forever
    inet6 2003::[snip]:b0ac/64 scope global dynamic noprefixroute 
       valid_lft 172794sec preferred_lft 86394sec
    inet6 fe80::[snip]:4ac5:6092/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

Router Screenshot:
![image](https://user-images.githubusercontent.com/22171518/233487291-c5b338ea-7088-4d1c-ac0b-d32f862afa0e.png)

When I then try: `ssh biqu@192.168.178.17` the connection times out.
`ssh biqu@[2003::[snip]:b0ac]` works fine.

I really can't explain this one...
When I connect ethernet I can reach the IPv4 of the wifi adapter. But i figure it then goes via LAN to reach the IPv4 on the CB1 and it's not magically fixed...

I have modified `/etc/NetworkManager/system-connections/MyWifi.nmconnection` to use a static IPv4 like so:
```
[...]
[ipv4]
dns-search=
method=manual
address1=192.168.178.17/24,192.168.178.1
dns=1.1.1.1;8.8.8.8
[...]
```

Thanks in advance!

Additional Info:
OS: CB1-v2.3.2 ([CB1_Debian11_minimal_kernel5.16_20230303.img.xz](https://github.com/bigtreetech/CB1/releases/download/V2.3.2/CB1_Debian11_minimal_kernel5.16_20230303.img.xz))
Kernel: `Linux klippy 5.16.17-sun50iw9 #2.3.2 SMP Fri Mar 3 17:05:59 HKT 2023 aarch64 GNU/Linux`

**Comment by LsHallo** [comment]
Solved...
I have removed the static IP from eth0 and now wlan0 is working as expected. Don't know why one influences the other...

**Comment by Avarios** [comment]
> 

How did you do that ?

**Comment by LsHallo** [comment]
> How did you do that ?

I used network manager to edit my connections. You can use the terminal ui for that: `nmtui` and then navigate with arrow keys, tab and enter.

**Comment by borinet** [comment]
Thank you for that command nmtui it work for me to set up my static ip
