### ISSUE TITLE
CB1 eMMC stuck in loading screen

### ISSUE THREAD

**Issue by tbs-trappy** [bigtreetech/CB1#114]
Hi,

I flashed the minimal debian using raspberry pi imager and default CM4 adapter board by Raspberry. The flashing went fine. I then disabled the boot flag and rebooted the unit. Now the screen is stuck in a perpetual booting screen showing Bigtreetech logo and a loading animation. How can I proceed to boot into debian?

I have also tried using the CM4-DISP-BASE-5A, and the output does not show up on the screen. I had to connect and external HDMI monitor to see the image.

**Comment by Pneumanifest** [comment]
Did you add needs_root_rights=yes to /etc/X11/Xwrapper.config (sudo nano /etc/X11/Xwrapper.config, add needs_root_rights=yes)

**Comment by tbs-trappy** [comment]
How would I do that? The device doesn't open through SSH, and I can't enter the console. All I see is a loading screen

**Comment by tbs-trappy** [comment]
![image](https://user-images.githubusercontent.com/9442218/235310169-6d360610-5881-4e83-bc2a-ea9f750e022e.png)
![image](https://user-images.githubusercontent.com/9442218/235310181-605e0d9e-704e-4124-923a-42a1cef0e94a.png)

**Comment by Pneumanifest** [comment]
Oh I misread your post. I thought it was just klipper screen that wasn't booting. Why would you disable the boot flag? Those are normally set to direct to the boot parton to get things started. It's probably best to re-burn the image and don't disable the boot flag.

**Comment by tbs-trappy** [comment]
You have to disable the bootloader jumper, otherwise you just get into the burn mode. I have re-burnt several times now, and I never get past this screen. I am not trying to use this for Klipper btw, I just want to run vanilla debian. I assume the minimal image is for that.

**Comment by Pneumanifest** [comment]
Oh I see what you are saying now, the physical boot switch on that board to go from OTG to boot. I thought you were disabling a boot flag in the system. 
When you were done flashing, before taking it out of OTG mode, did you go into the BoardEnv.txt in the boot partition and edit the fdtfile line to read,  ```fdtfile=sun50i-h616-biqu-emmc``` ? You will also need to input your wifi info in the system.cfg file if you are planning to use that.

As for the screen, there's a chance that the CB1 doesn't support DIP interface. I definitely doesn't support DSI. I know that HDMI and SPI are supported though.

**Comment by tbs-trappy** [comment]
thanks. I will try that right away, I did not change the fdtfile. and yes, the screen seems not to be compatible. I will need to wait for bigtreetech's CB1 screen to become available next week.

having high hopes that this can replace my CM4s. I just need a linux console and a USB driver. not using it for 3D printing.

**Comment by Pneumanifest** [comment]
If you haven't seen it already, make sure to read about the gpio assignment in the user guide for the cb1. They are not the same numbers as the raspberry pi. There is a formula to use to get the correct gpio numbers.

**Comment by tbs-trappy** [comment]
that fixed it, thanks!
