### ISSUE TITLE
Klipper error on Manta E3EZ

### ISSUE THREAD

**Issue by BrodoDeluxe** [bigtreetech/CB1#120]
After flashing the firmware, the CB1 connects to the wifi but then Moonraker won't work. Tried different releases of the Debian Bullseye  but none of them works. Klipper gives this error: "Include file '/home/biqu/printer_data/config/generic-bigtreetech-xxxx.cfg' does not exist"

**Comment by Pneumanifest** [comment]
Moonraker is working, that is saying you need to make a configuration for you machine. There is a place holder  [include generic-bigtreetech-xxxx.cfg] in the printer.cfg to show you that you need to make one  and replace the generic-bigtreetech-xxxx.cfg with the whatever-board-you-have.cfg. So if you have a Manta M5p you'll make a Manta-m5p.cfg with your printer specific parameters and in the printer.cfg file you make it [include Manta-m5p.cfg]
