### ISSUE TITLE
TFT35 SPI

### ISSUE THREAD

**Issue by Sonnenwerk** [bigtreetech/CB1#129]
I connected the TFT35 to CB1/e3EZ and it generally works, but i can not reach the "buttons" on the left side, because the "touch for the icons to work" are too close to the boarder. How can i set an offset or recalibrate touch vs. screen ? Found no documentation for it

**Comment by bigtreetech** [comment]
solve in https://bigtreetech.github.io/docs/libinput_calibration.html

**Comment by Sonnenwerk** [comment]
Thanks a lot !
