### ISSUE TITLE
CB1 internal temperature monitoring?

### ISSUE THREAD

**Issue by Valiance** [bigtreetech/CB1#140]
The CB1 unit burns hot at times.   Is there a safety internal temperature monitor for max temp shut down?   Is there a more civil internal temperature reporting it does to the OS, or say... Klipper?  Like a temp sensor I could use to trigger a fan2 on/off?  This could help prevent forest fires...    If not, perhaps getting an official statement from BTT in the form of a warning: 'There is not an internal temperature monitoring system available for the CB1'  Granted, I know that is a bit much, but still... asking.

**Comment by Pneumanifest** [comment]
This will get you the temperature in klipper,

``` [temperature_sensor CB1]
sensor_type: temperature_host
 ```
Or install ls-sensors terminal,
```
sudo apt install ls-sensors
``` 
When that is done run command,
```
sensors 
```

**Comment by Valiance** [comment]
Thank you so much, Patrick.    This is beautiful.

**Comment by 420noscope-exe** [comment]
@Valiance make sure to close you issue if it was answered

**Comment by Valiance** [comment]
Yes, it is working.
"Reality is the Ultimate Role-playing game." -- Victor A. Waters '88
