### ISSUE TITLE
boot on m.2 nvme drive

### ISSUE THREAD

**Issue by willpuckett** [bigtreetech/CB1#145]
Is it possible to boot cb1 from an nvme drive? 

I'm using cb1 on a [waveshare mini baseboard](https://www.waveshare.com/cm4-io-base-a.htm). It has a m.2 slot on the back side that is for an nvme drive. 

When I put the m.2 drive in an enclosure, I can mount it over usb. The m.2 nvme drive doesn't show up at all though when it's in the m.2 slot (even if the cb1 is booted from sd card).

**Comment by frutabruta** [comment]
Not possible. The m.2 slot requires PCI or SATA which are not present on CB1.
