### ISSUE TITLE
BTTPI randomly disconnect USB device

### ISSUE THREAD

**Issue by shine7k** [bigtreetech/CB1#147]
When btt pi is connected to multiple USB devices at the same time, one of them will be disconnected randomly.
btt pi+skr pico +ebb36    use u2c
btt pi is connected to pico  and ebb36 through USB cables
ebb36 disconnected soon after linux started
Sometimes pico is disconnected
my btt pi with the following image: CB1_Debian11_Klipper_kernel5.16_202300712.img.xz

**Comment by shine7k** [comment]
After disconnecting the PICO, it will not be randomly cut off. It can always be connected to EBB36
~/klippy-env/bin/python ~/klipper/scripts/canbus_query.py can0
Total 1 uuids found

**Comment by frutabruta** [comment]
I have similiar problem with my CB1 plugged into Manta M8P. The U2C gets disconnected after pluging in the BTT HDMI5 to the USB port. Everything works after I reboot the system.

**Comment by Spil7Milk** [comment]
I also have a similar issue with my CB1 / Manta E3EZ, the board randomly loses connection with the MCU.  During my testing I have found that having the HDMI 5 connected is what is causing the issue.  Not sure if it is the CB1 or HDMI5 that is at fault, but reading everyone's comments I am leaning more towards CB1.

**Comment by shine7k** [comment]
I think this is not a problem. After the Klipper is successful in the CanBus, it will not be displayed in the display "Total" through the command line, because the Klipper has been successfully connected to the device. It's okay.
