### ISSUE TITLE
[FR] armbian-config: Move to eMMC

### ISSUE THREAD

**Issue by Sineos** [bigtreetech/CB1#148]
Typically, Armbian offers to move the OS to the eMMC from within `armbian-confgi`:

![grafik](https://github.com/bigtreetech/CB1/assets/4459312/c050e245-e1e6-4778-925f-7c83eeae0eab)

Currently, this seems not the case for the CB1, so I would like to kindly request adding this possibility.

**Comment by bigtreetech** [comment]
add `nand-sata-install` move to emmc in https://github.com/bigtreetech/CB1-Kernel/commit/e6663e165326da4ec7bdabab94032fe946c1c52d
