### ISSUE TITLE
Manta M8P v2 + CB1 eMMC install

### ISSUE THREAD

**Issue by manotroll** [bigtreetech/CB1#177]
How do I copy the files from the micro SD to the eMMC and start booting from it?

**Comment by frutabruta** [comment]
1) the SD card needs to be smaller/same size as the eMMC in CB1
2) insert SD card into PC
3) download Win32DiskImager and create image of the SD card by selecting the drive letter, path for the resulting image and click Read.
4) get back to homepage of this repository ( https://github.com/bigtreetech/CB1 ) and do the stuff mentioned in the **CB1 eMMC Version** section.

**Comment by manotroll** [comment]
Thank you, it is working with a transfer rate of 4MB/s, this is ultra slow
Starting the system won't be so slow, right?
