### ISSUE TITLE
Unable to obtain 'spi_transfer_response' response /MCU 'mcu' shutdown: Timer too close CB1 Emmc

### ISSUE THREAD

**Issue by Martin11180** [bigtreetech/CB1#186]
BIGTREETECH Manta M8P V2
EBB 2209 / RP2040
TFT35 SPI V2.1 
CB1 emmc board
mcu EBBCan(rp2040)

Board und EBB neu geflasht
mcu EBBCan(rp2040)
Version: v0.12.0-230-g0d87bec1
Auslastung: 0.05, Wach: 0.22, Freq: 12 MHz, 
mcu(stm32h723xx)
Version: v0.12.0-237-gfcf064ba
Auslastung: 0.00, Wach: 0.01, Freq: 400 MHz, Temp: 44°C 

I don't know if it's a bug or a setting problem
When I run the Input Shaper and then call Home or other functions
there is a message
in the console
Unable to obtain 'spi_transfer_response' response

klipper 
Klipper meldet: SHUTDOWN

MCU 'mcu' shutdown: Timer too close

When I tried switching to an SD card, everything worked
[boardenv.txt](https://github.com/user-attachments/files/15844225/boardenv.txt)
[klippy(73).log](https://github.com/user-attachments/files/15844226/klippy.73.log)
[system.cfg.txt](https://github.com/user-attachments/files/15844234/system.cfg.txt)

greet 
Martin

**Comment by KD-4-Lyfe** [comment]
if your still having issues with this i seem to have solved it by doing this:

[adxl345]
cs_pin: PA15
spi_bus: spi3a

had some other settings (shown below) which seem to be playing up which i got from someone else cause i was having other issues

-# [adxl345]
-# cs_pin: PA15
-# spi_software_sclk_pin: PC10
-# spi_software_mosi_pin: PC12
-# spi_software_miso_pin: PC11
-# spi_speed: 25000000
-# rate: 3200

apart from that check your wiring, i had to redo mine
