### ISSUE TITLE
full specifications of `system.cfg` needed

### ISSUE THREAD

**Issue by vtta** [bigtreetech/CB1#19]
I need the ability to add custom kernel command line arguments. Currently there is no obvious way to do this. I want to know if such modifications could be achieved using `system.cfg`. So it would be easier if you can provide the full specifications of this config file. Or the better way is to just open source the whole source code, so that we can build our own distribution or kernel image.

**Comment by shawnchr** [comment]
You cannot pass kernel params via this file system.cfg is used as a variable in the /etc/wifi_config.sh and it is call by the /etc/NMconnection script that starts NetworkManager that manages the network interfaces.

[biqu@Micron1 ~]$ cat /etc/wifi_config.sh 
#!/bin/bash


WIFI_CONFIG_SSID=(null null)
WIFI_CONFIG_PASSWORD=(null null)

INDEX=0


WIFI_CONFIG_FILE=/mnt/udisk/system.cfg

**Comment by ghent360** [comment]
Kernel params are on the second partition of the sdcard image. Not sure what the format of the partition is, probably uboot something, but you can see the kernel params as clear text.

**Comment by vtta** [comment]
Than

> Kernel params are on the second partition of the sdcard image. Not sure what the format of the partition is, probably uboot something, but you can see the kernel params as clear text.

Thanks for the info, I will give it a try 👍

**Comment by VIXIVIXIV** [comment]
> > Kernel params are on the second partition of the sdcard image. Not sure what the format of the partition is, probably uboot something, but you can see the kernel params as clear text.
> 
> Thanks for the info, I will give it a try 👍

Do you have any further updates on passing kernel parameters? I haven't been able to get it to work either.

**Comment by vtta** [comment]
No. I have already ditched the CB1 due to super bad WiFi card and lack of source code. Now I have switched to CM4.
