### ISSUE TITLE
Octoprint + CB1?

### ISSUE THREAD

**Issue by Aleks-MO** [bigtreetech/CB1#2]
Would you like to see the installation of **Octoprint** on **CB1** ?

**Comment by escvn54** [comment]
I would definitely like to see this.  Even better, a barebones CB1 Ubuntu image with nothing installed, so the end user can decide what to install.

**Comment by astrof** [comment]
I was under the impression the reason for these was for Klipper and octoprint

**Comment by escvn54** [comment]
> I was under the impression the reason for these was for Klipper and octoprint

You're absolutely right, but I would rather have the clean slate to start with, so I can install only what I want installed.

**Comment by astrof** [comment]
So obviously the correct answer is...have both! Have a clean image version and one that has the 3D Printer tools (and/or whatever else normal BTT customers use) installed (or instructions on how to install)

**Comment by bigtreetech** [comment]
Hello. Every one. The minimal Debian is released in [here](https://github.com/bigtreetech/CB1/releases).  And we can discuss the optimization and improvement [here](https://github.com/bigtreetech/CB1/discussions/9)

**Comment by Will-wastelander** [comment]
I second a vanilla image. What if I don't plan to use the CB1 for 3D
Printing tasks, and want to use it for something else m
