### ISSUE TITLE
NFSD running

### ISSUE THREAD

**Issue by MichaelAronsen** [bigtreetech/CB1#3]
After flashing the debian based image and starting it up, I saw nfsd running, but no shares defined in /etc/exports.

This is a waste of resources, so systemctl stop nfs-server and systemctl disable nfs-server helps.

Probably more services are enabled that don't need to be, if you'd like me to, I could go through them all?

**Comment by Will-wastelander** [comment]
Is eth0 detected on your CB1 if you have the pi4b adapter m

**Comment by MichaelAronsen** [comment]
shows up as eth1, but yeah
