### ISSUE TITLE
Update apt mirrors list

### ISSUE THREAD

**Issue by yzheka** [bigtreetech/CB1#55]
Provided mirrors list (/etc/apt/sources.list) from China apt servers are very slow. Maybe add some tool that will generate them according to current timezone/location?

**Comment by Tompudex** [comment]
> 

https://wiki.debian.org/SourcesList
here is the normal list.  nano the .list and change it

**Comment by yzheka** [comment]
I guess in v2.2.1 release it is fixed according to the description:
Use standard Debian source to replace Tsinghua source.
