### ISSUE TITLE
git clone does not work

### ISSUE THREAD

**Issue by frutabruta** [bigtreetech/CB1#6]
Every git clone end up with 
`
'Failed to connect to 192.168.0.126 port 7890: Connection timed out'
`

This IP is specified in .gitconfig file:
```
biqu@Hurakan:~$ ack "192.168.0.126"
.gitconfig
2:      proxy = http://192.168.0.126:7890/
4:      proxy = https://192.168.0.126:7890/
```
Which  can be resolved with two commands:

```
git config --global --unset https.proxy
git config --global --unset http.proxy
```

**Comment by emesix** [comment]
Try this: git config --global --unset http.proxy

**Comment by emesix** [comment]
Dear BigTreeTech,

Is there anyway to get a empty minimal install of Debian for the CB1? The last ISO image is full of proxy settings, personalized shell configurations and preinstalled non release software. Compiling the klipper software for the M8P fails on a normal SSH login because of missing en_US locale!

**Comment by bigtreetech** [comment]
> Dear BigTreeTech,
> 
> Is there anyway to get a empty minimal install of Debian for the CB1? The last ISO image is full of proxy settings, personalized shell configurations and preinstalled non release software. Compiling the klipper software for the M8P fails on a normal SSH login because of missing en_US locale!

The Debian11 file system is being ported. The minimal OS of Debian version will be released before tomorrow. Thank you for your support

**Comment by bigtreetech** [comment]
> Dear BigTreeTech,
> 
> Is there anyway to get a empty minimal install of Debian for the CB1? The last ISO image is full of proxy settings, personalized shell configurations and preinstalled non release software. Compiling the klipper software for the M8P fails on a normal SSH login because of missing en_US locale!

Hello. The minimal Debian is released in [here](https://github.com/bigtreetech/CB1/releases).  And we can discuss the optimization and improvement [here](https://github.com/bigtreetech/CB1/discussions/9)

**Comment by frutabruta** [comment]
This issue has been solved in new images.
