### ISSUE TITLE
Is the virtual_sdcard path different?

### ISSUE THREAD

**Issue by 4e576rt8uh9ij9okp** [bigtreetech/CB1#88]
I'm getting an error saying
"Unable to open file"

No idea if it's a permission thing or what's wrong.
I can't also find a "gcode_files" folder on Mainsail.

**Comment by Pneumanifest** [comment]
It should be set up to be in 
    ~/printer_data/gcodes

And in your mainsail.cfg add this,
    [virtual_sdcard]
    path: ~/printer_data/gcodes
    on_error_gcode:
      CANCEL_PRINT
